(()=>{function w(){console.log("wzl script injected");let e=window.location.href.trim(),t={job_application_submit_page:/https:\/\/www.wyzant.com\/tutor\/jobs\/\d+/,message_page:/https:\/\/www.wyzant.com\/tutor\/messaging/},[n]=Object.entries(t).filter(([r,l])=>e.match(l)).map(([r])=>r);switch(console.log("wlz page target",n),n){case"message_page":console.log("wzl message_page"),S(),q();break;case"job_application_submit_page":{console.log("wzl job_application_submit_page"),v();break}default:break}}function v(){let e=document.querySelector("input[name=hourly_rate]");e.setAttribute("type","number"),e.setAttribute("step","5"),y(document.querySelector(".hourly-rate-label + p"),e),g(),z()}function z(){document.querySelector("input[type=submit]").focus()}function y(e,t){if(!t||!e)return;let[n]=e.textContent.match(/\d*$/);if(Number(n)>t.value)if(console.log("high offer present"),Number(n)<=70)console.log("charge exact offer"),t.value=Number(n);else{console.log("charging base plus difference");let r=.6*(Number(n)-70);t.value=Math.ceil((70+r)/5)*5}}function g(){let e=Array.from(document.querySelectorAll("select[name=template_select] > option").values()).find(({textContent:t})=>t==="default application");!e||(document.querySelector("select[name=template_select]").value=e.value,document.querySelector("textarea#personal_message").value=e.value)}async function s(e){let t=document.querySelector(".wzl-profile");if(t&&t.remove(),E(),console.log("messageDocumentClickHandler fired"),!b(e.currentTarget)){console.log("target is not a .conversation-summary-wrap");return}let r=document.querySelector(".selected p.username");if(!r)return;let[l]=r.textContent.trim().split(" "),{iframe:i,is_new:m}=u();console.log({selected_student:r}),m&&(document.querySelector(".wzl-container").appendChild(i),await new Promise(p=>{let f=setInterval(()=>{console.log("interval running"),Array.from(document.querySelector(".wzl_iframe").contentWindow.document.querySelectorAll(".job-result")).length&&(clearInterval(f),p("ready"))},400)})),j();let o=document.querySelector(".wzl-profile");o||(o=document.createElement("div"),document.querySelector(".wzl-container").appendChild(o)),o.classList.add("wzl-profile"),o.innerHTML=_(k(L(i,l))),document.querySelector(".wzl-card--close").addEventListener("click",()=>a(!1)),document.querySelector(".wzl-card--reset").addEventListener("click",()=>a(!0))}function b(e){return e.closest(".conversation-summary-wrap")}function S(){if(document.querySelector(".wzl-container"))return;let e=document.createElement("div");e.classList.add("wzl","wzl-container"),e.appendChild(h()),document.body.appendChild(e),console.log("wzl-container appended to body")}function _(e){if(!!e)return`
	<div class="wzl-card">
		<span class="wzl-card--close">X</span>
		<span class="wzl-card--reset">Close & Reset</span>
		<div class="wzl-card--avatar"></div>
		<div class="wzl-card--body wzl-student">
			<p class="wzl-student--username">${e.title}</p>
			<p class="wzl-student--subject">${e.time}</p>
			<p class="wzl-student--description">${e.description}</p>
		</div>
	</div>
	`}function a(e){if(document.querySelector(".wzl-card").remove(),e??!1){let{iframe:t}=u();t.remove(),Array.from(document.querySelectorAll(".conversation-summary-wrap")).filter(n=>n.classList.contains("wzl-listener-active")).forEach(n=>{n.classList.remove("wzl-listener-active"),n.removeEventListener("click",s)}),document.querySelector(".show-more a.btn").removeEventListener("click",c),d()}}function h(){let e='<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>',t=document.createElement("div");return t.classList.add("wzl-spinner-container"),t.innerHTML=e,t}function u(){let e=document.querySelector("#wzl_iframe");if(e)return{iframe:e,is_new:!1};let t=document.createElement("iframe");return t.setAttribute("width","300"),t.setAttribute("height","200"),t.classList.add("wzl_iframe"),t.setAttribute("id","wzl_iframe"),t.setAttribute("src","https://www.wyzant.com/tutor/jobapplication/history?sort=1&pagenumber=0&pagesize=100"),{iframe:t,is_new:!0}}function q(){let e=document.querySelector(".wzl-container"),t=document.createElement("button");t.textContent="Wzl Ready",t.classList.add("wzl_indicator"),t.setAttribute("tooltip","Click to enable profile lookup of students (underlined)"),e.appendChild(t),t.addEventListener("click",A)}function A(e){let t=Array.from(document.querySelectorAll(".conversation-summary-wrap")).filter(n=>!n.classList.contains("wzl-listener-active"));t.length&&(t.forEach(n=>{n.classList.add("wzl-listener-active"),n.addEventListener("click",s)}),C()),document.querySelector(".show-more a.btn").removeEventListener("click",c),document.querySelector(".show-more a.btn").addEventListener("click",c)}function c(e){d()}function C(){document.querySelector(".wzl_indicator").classList.add("wzl_indicator_active")}function d(){document.querySelector(".wzl_indicator").classList.remove("wzl_indicator_active")}function L(e,t){console.log("findStudentResult called");let n=e.contentWindow.document.querySelectorAll(".job-result");return Array.from(n).find(i=>i.textContent.includes(t))}function k(e){return e?{title:e.querySelector(".job-result h4").textContent,time:e.querySelectorAll(".job-result p")[2].textContent,description:e.querySelectorAll(".job-result p")[0].textContent}:{title:"Info not found",time:"Info not found",description:"Info not found in recent 100 submitted job applications"}}function E(){document.querySelector(".wzl-spinner-container").classList.add("show")}function j(){document.querySelector(".wzl-spinner-container").classList.remove("show")}w();})();
