name: Release and publish on tag
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
    branches: [master]

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
     
      - name: update manifest version to release version
        run: |
            ext_version_name=${{github.ref_name}}
            echo $ext_version_name
            ext_version_id=$(echo $ext_version_name | tr -d [:alpha:] | tr -d [=-=])
            sed -i "s/0.0.8/$ext_version_id/" manifest.json
            sed -i "s/VERSION_NAME/$ext_version_name/" manifest.json
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: | 
            npm i 
            npm run prod
            npm run package
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/wyzant-looker.zip, dist/changelog.md"
          token: ${{ secrets.GITHUB_TOKEN }}
