name: Tag & Release project
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main,master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Bump Version"
        uses: marier-nico/pr-bump@v1.0.0
        with:
          configuration: ".github/workflows/pr_bump_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}